package com.pqi.responsecompare.edi.mp.enums;

import java.util.HashMap;

public enum ISO639 {

    Instance;

    private static HashMap<String,String> iso639 = new HashMap<String,String>();

    public String getISO639(String key) {
        String result = "English";
        if (iso639.containsKey(key)) {
            result = iso639.get(key);
        }
        return result;
    }

    static {
        iso639.put("UND", "English");
        iso639.put("aar", "Afar");
        iso639.put("abk", "Abkhazian");
        iso639.put("ace", "Achinese");
        iso639.put("ach", "Acoli");
        iso639.put("ada", "Adangme");
        iso639.put("ady", "Adyghe; Adygei");
        iso639.put("afa", "Afro-Asiatic languages");
        iso639.put("afh", "Afrihili");
        iso639.put("afr", "Afrikaans");
        iso639.put("ain", "Ainu");
        iso639.put("aka", "Akan");
        iso639.put("akk", "Akkadian");
        iso639.put("alb", "(B)	Albanian");
        iso639.put("sqi", "(T)");
        iso639.put("ale", "Aleut");
        iso639.put("alg", "Algonquian languages");
        iso639.put("alt", "Southern Altai");
        iso639.put("amh", "Amharic");
        iso639.put("ang", "English, Old (ca.450-1100)");
        iso639.put("anp", "Angika");
        iso639.put("apa", "Apache languages");
        iso639.put("ara", "Arabic");
        iso639.put("arc", "Official Aramaic (700-300 BCE); Imperial Aramaic (700-300 BCE)");
        iso639.put("arg", "Aragonese");
        iso639.put("arm", "(B)	Armenian");
        iso639.put("hye", "(T)");
        iso639.put("arn", "Mapudungun; Mapuche");
        iso639.put("arp", "Arapaho");
        iso639.put("art", "Artificial languages");
        iso639.put("arw", "Arawak");
        iso639.put("asm", "Assamese");
        iso639.put("ast", "Asturian; Bable; Leonese; Asturleonese");
        iso639.put("ath", "Athapascan languages");
        iso639.put("aus", "Australian languages");
        iso639.put("ava", "Avaric");
        iso639.put("ave", "Avestan");
        iso639.put("awa", "Awadhi");
        iso639.put("aym", "Aymara");
        iso639.put("aze", "Azerbaijani");
        iso639.put("bad", "Banda languages");
        iso639.put("bai", "Bamileke languages");
        iso639.put("bak", "Bashkir");
        iso639.put("bal", "Baluchi");
        iso639.put("bam", "Bambara");
        iso639.put("ban", "Balinese");
        iso639.put("baq", "(B)	Basque");
        iso639.put("eus", "(T)");
        iso639.put("bas", "Basa");
        iso639.put("bat", "Baltic languages");
        iso639.put("bej", "Beja; Bedawiyet");
        iso639.put("bel", "Belarusian");
        iso639.put("bem", "Bemba");
        iso639.put("ben", "Bengali");
        iso639.put("ber", "Berber languages");
        iso639.put("bho", "Bhojpuri");
        iso639.put("bih", "Bihari languages");
        iso639.put("bik", "Bikol");
        iso639.put("bin", "Bini; Edo");
        iso639.put("bis", "Bislama");
        iso639.put("bla", "Siksika");
        iso639.put("bnt", "Bantu languages");
        iso639.put("tib", "(B)	Tibetan");
        iso639.put("bod", "(T)");
        iso639.put("bos", "Bosnian");
        iso639.put("bra", "Braj");
        iso639.put("bre", "Breton");
        iso639.put("btk", "Batak languages");
        iso639.put("bua", "Buriat");
        iso639.put("bug", "Buginese");
        iso639.put("bul", "Bulgarian");
        iso639.put("bur", "(B)	Burmese");
        iso639.put("mya", "(T)");
        iso639.put("byn", "Blin; Bilin");
        iso639.put("cad", "Caddo");
        iso639.put("cai", "Central American Indian languages");
        iso639.put("car", "Galibi Carib");
        iso639.put("cat", "Catalan; Valencian");
        iso639.put("cau", "Caucasian languages");
        iso639.put("ceb", "Cebuano");
        iso639.put("cel", "Celtic languages");
        iso639.put("cze", "(B)	Czech");
        iso639.put("ces", "(T)");
        iso639.put("cha", "Chamorro");
        iso639.put("chb", "Chibcha");
        iso639.put("che", "Chechen");
        iso639.put("chg", "Chagatai");
        iso639.put("chi", "(B)	Chinese");
        iso639.put("zho", "(T)");
        iso639.put("chk", "Chuukese");
        iso639.put("chm", "Mari");
        iso639.put("chn", "Chinook jargon");
        iso639.put("cho", "Choctaw");
        iso639.put("chp", "Chipewyan; Dene Suline");
        iso639.put("chr", "Cherokee");
        iso639.put("chu", "Church Slavic; Old Slavonic; Church Slavonic; Old Bulgarian; Old Church");
        iso639.put("chv", "Chuvash");
        iso639.put("chy", "Cheyenne");
        iso639.put("cmc", "Chamic languages");
        iso639.put("cnr", "Montenegrin");
        iso639.put("cop", "Coptic");
        iso639.put("cor", "Cornish");
        iso639.put("cos", "Corsican");
        iso639.put("cpe", "Creoles and pidgins, English based");
        iso639.put("cpf", "Creoles and pidgins, French-based");
        iso639.put("cpp", "Creoles and pidgins, Portuguese-based");
        iso639.put("cre", "Cree");
        iso639.put("crh", "Crimean Tatar; Crimean Turkish");
        iso639.put("crp", "Creoles and pidgins");
        iso639.put("csb", "Kashubian");
        iso639.put("cus", "Cushitic languages");
        iso639.put("wel", "(B)	Welsh");
        iso639.put("cym", "(T)");
        iso639.put("cze", "(B)	Czech");
        iso639.put("ces", "(T)");
        iso639.put("dak", "Dakota");
        iso639.put("dan", "Danish");
        iso639.put("dar", "Dargwa");
        iso639.put("day", "Land Dayak languages");
        iso639.put("del", "Delaware");
        iso639.put("den", "Slave (Athapascan)");
        iso639.put("ger", "(B)	German");
        iso639.put("deu", "(T)");
        iso639.put("dgr", "Dogrib");
        iso639.put("din", "Dinka");
        iso639.put("div", "Divehi; Dhivehi; Maldivian");
        iso639.put("doi", "Dogri");
        iso639.put("dra", "Dravidian languages");
        iso639.put("dsb", "Lower Sorbian");
        iso639.put("dua", "Duala");
        iso639.put("dum", "Dutch, Middle (ca.1050-1350)");
        iso639.put("dut", "(B)	Dutch; Flemish");
        iso639.put("nld", "(T)");
        iso639.put("dyu", "Dyula");
        iso639.put("dzo", "Dzongkha");
        iso639.put("efi", "Efik");
        iso639.put("egy", "Egyptian (Ancient)");
        iso639.put("eka", "Ekajuk");
        iso639.put("gre", "(B)	Greek, Modern (1453-)");
        iso639.put("ell", "(T)");
        iso639.put("elx", "Elamite");
        iso639.put("eng", "English");
        iso639.put("enm", "English, Middle (1100-1500)");
        iso639.put("epo", "Esperanto");
        iso639.put("est", "Estonian");
        iso639.put("baq", "(B)	Basque");
        iso639.put("eus", "(T)");
        iso639.put("ewe", "Ewe");
        iso639.put("ewo", "Ewondo");
        iso639.put("fan", "Fang");
        iso639.put("fao", "Faroese");
        iso639.put("per", "(B)	Persian");
        iso639.put("fas", "(T)");
        iso639.put("fat", "Fanti");
        iso639.put("fij", "Fijian");
        iso639.put("fil", "Filipino; Pilipino");
        iso639.put("fin", "Finnish");
        iso639.put("fiu", "Finno-Ugrian languages");
        iso639.put("fon", "Fon");
        iso639.put("fre", "(B)	French");
        iso639.put("fra", "(T)");
        iso639.put("fre", "(B)	French");
        iso639.put("fra", "(T)");
        iso639.put("frm", "French, Middle (ca.1400-1600)");
        iso639.put("fro", "French, Old (842-ca.1400)");
        iso639.put("frr", "Northern Frisian");
        iso639.put("frs", "Eastern Frisian");
        iso639.put("fry", "Western Frisian");
        iso639.put("ful", "Fulah");
        iso639.put("fur", "Friulian");
        iso639.put("gaa", "Ga");
        iso639.put("gay", "Gayo");
        iso639.put("gba", "Gbaya");
        iso639.put("gem", "Germanic languages");
        iso639.put("geo", "(B)	Georgian");
        iso639.put("kat", "(T)");
        iso639.put("ger", "(B)	German");
        iso639.put("deu", "(T)");
        iso639.put("gez", "Geez");
        iso639.put("gil", "Gilbertese");
        iso639.put("gla", "Gaelic; Scottish Gaelic");
        iso639.put("gle", "Irish");
        iso639.put("glg", "Galician");
        iso639.put("glv", "Manx");
        iso639.put("gmh", "German, Middle High (ca.1050-1500)");
        iso639.put("goh", "German, Old High (ca.750-1050)");
        iso639.put("gon", "Gondi");
        iso639.put("gor", "Gorontalo");
        iso639.put("got", "Gothic");
        iso639.put("grb", "Grebo");
        iso639.put("grc", "Greek, Ancient (to 1453)");
        iso639.put("gre", "(B)	Greek, Modern (1453-)");
        iso639.put("ell", "(T)");
        iso639.put("grn", "Guarani");
        iso639.put("gsw", "Swiss German; Alemannic; Alsatian");
        iso639.put("guj", "Gujarati");
        iso639.put("gwi", "Gwich'in");
        iso639.put("hai", "Haida");
        iso639.put("hat", "Haitian; Haitian Creole");
        iso639.put("hau", "Hausa");
        iso639.put("haw", "Hawaiian");
        iso639.put("heb", "Hebrew");
        iso639.put("her", "Herero");
        iso639.put("hil", "Hiligaynon");
        iso639.put("him", "Himachali languages; Western Pahari languages");
        iso639.put("hin", "Hindi");
        iso639.put("hit", "Hittite");
        iso639.put("hmn", "Hmong; Mong");
        iso639.put("hmo", "Hiri Motu");
        iso639.put("hrv", "Croatian");
        iso639.put("hsb", "Upper Sorbian");
        iso639.put("hun", "Hungarian");
        iso639.put("hup", "Hupa");
        iso639.put("arm", "(B)	Armenian");
        iso639.put("hye", "(T)");
        iso639.put("iba", "Iban");
        iso639.put("ibo", "Igbo");
        iso639.put("ice", "(B)	Icelandic");
        iso639.put("isl", "(T)");
        iso639.put("ido", "Ido");
        iso639.put("iii", "Sichuan Yi; Nuosu");
        iso639.put("ijo", "Ijo languages");
        iso639.put("iku", "Inuktitut");
        iso639.put("ile", "Interlingue; Occidental");
        iso639.put("ilo", "Iloko");
        iso639.put("ina", "Interlingua (International Auxiliary Language Association)");
        iso639.put("inc", "Indic languages");
        iso639.put("ind", "Indonesian");
        iso639.put("ine", "Indo-European languages");
        iso639.put("inh", "Ingush");
        iso639.put("ipk", "Inupiaq");
        iso639.put("ira", "Iranian languages");
        iso639.put("iro", "Iroquoian languages");
        iso639.put("ice", "(B)	Icelandic");
        iso639.put("isl", "(T)");
        iso639.put("ita", "Italian");
        iso639.put("jav", "Javanese");
        iso639.put("jbo", "Lojban");
        iso639.put("jpn", "Japanese");
        iso639.put("jpr", "Judeo-Persian");
        iso639.put("jrb", "Judeo-Arabic");
        iso639.put("kaa", "Kara-Kalpak");
        iso639.put("kab", "Kabyle");
        iso639.put("kac", "Kachin; Jingpho");
        iso639.put("kal", "Kalaallisut; Greenlandic");
        iso639.put("kam", "Kamba");
        iso639.put("kan", "Kannada");
        iso639.put("kar", "Karen languages");
        iso639.put("kas", "Kashmiri");
        iso639.put("geo", "(B)	Georgian");
        iso639.put("kat", "(T)");
        iso639.put("kau", "Kanuri");
        iso639.put("kaw", "Kawi");
        iso639.put("kaz", "Kazakh");
        iso639.put("kbd", "Kabardian");
        iso639.put("kha", "Khasi");
        iso639.put("khi", "Khoisan languages");
        iso639.put("khm", "Central Khmer");
        iso639.put("kho", "Khotanese; Sakan");
        iso639.put("kik", "Kikuyu; Gikuyu");
        iso639.put("kin", "Kinyarwanda");
        iso639.put("kir", "Kirghiz; Kyrgyz");
        iso639.put("kmb", "Kimbundu");
        iso639.put("kok", "Konkani");
        iso639.put("kom", "Komi");
        iso639.put("kon", "Kongo");
        iso639.put("kor", "Korean");
        iso639.put("kos", "Kosraean");
        iso639.put("kpe", "Kpelle");
        iso639.put("krc", "Karachay-Balkar");
        iso639.put("krl", "Karelian");
        iso639.put("kro", "Kru languages");
        iso639.put("kru", "Kurukh");
        iso639.put("kua", "Kuanyama; Kwanyama");
        iso639.put("kum", "Kumyk");
        iso639.put("kur", "Kurdish");
        iso639.put("kut", "Kutenai");
        iso639.put("lad", "Ladino");
        iso639.put("lah", "Lahnda");
        iso639.put("lam", "Lamba");
        iso639.put("lao", "Lao");
        iso639.put("lat", "Latin");
        iso639.put("lav", "Latvian");
        iso639.put("lez", "Lezghian");
        iso639.put("lim", "Limburgan; Limburger; Limburgish");
        iso639.put("lin", "Lingala");
        iso639.put("lit", "Lithuanian");
        iso639.put("lol", "Mongo");
        iso639.put("loz", "Lozi");
        iso639.put("ltz", "Luxembourgish; Letzeburgesch");
        iso639.put("lua", "Luba-Lulua");
        iso639.put("lub", "Luba-Katanga");
        iso639.put("lug", "Ganda");
        iso639.put("lui", "Luiseno");
        iso639.put("lun", "Lunda");
        iso639.put("luo", "Luo (Kenya and Tanzania)");
        iso639.put("lus", "Lushai");
        iso639.put("mac", "(B)	Macedonian");
        iso639.put("mkd", "(T)");
        iso639.put("mad", "Madurese");
        iso639.put("mag", "Magahi");
        iso639.put("mah", "Marshallese");
        iso639.put("mai", "Maithili");
        iso639.put("mak", "Makasar");
        iso639.put("mal", "Malayalam");
        iso639.put("man", "Mandingo");
        iso639.put("mao", "(B)	Maori");
        iso639.put("mri", "(T)");
        iso639.put("map", "Austronesian languages");
        iso639.put("mar", "Marathi");
        iso639.put("mas", "Masai");
        iso639.put("may", "(B)	Malay");
        iso639.put("msa", "(T)");
        iso639.put("mdf", "Moksha");
        iso639.put("mdr", "Mandar");
        iso639.put("men", "Mende");
        iso639.put("mga", "Irish, Middle (900-1200)");
        iso639.put("mic", "Mi'kmaq; Micmac");
        iso639.put("min", "Minangkabau");
        iso639.put("mis", "Uncoded languages");
        iso639.put("mac", "(B)	Macedonian");
        iso639.put("mkd", "(T)");
        iso639.put("mkh", "Mon-Khmer languages");
        iso639.put("mlg", "Malagasy");
        iso639.put("mlt", "Maltese");
        iso639.put("mnc", "Manchu");
        iso639.put("mni", "Manipuri");
        iso639.put("mno", "Manobo languages");
        iso639.put("moh", "Mohawk");
        iso639.put("mon", "Mongolian");
        iso639.put("mos", "Mossi");
        iso639.put("mao", "(B)	Maori");
        iso639.put("mri", "(T)");
        iso639.put("may", "(B)	Malay");
        iso639.put("msa", "(T)");
        iso639.put("mul", "Multiple languages");
        iso639.put("mun", "Munda languages");
        iso639.put("mus", "Creek");
        iso639.put("mwl", "Mirandese");
        iso639.put("mwr", "Marwari");
        iso639.put("bur", "(B)	Burmese");
        iso639.put("mya", "(T)");
        iso639.put("myn", "Mayan languages");
        iso639.put("myv", "Erzya");
        iso639.put("nah", "Nahuatl languages");
        iso639.put("nai", "North American Indian languages");
        iso639.put("nap", "Neapolitan");
        iso639.put("nau", "Nauru");
        iso639.put("nav", "Navajo; Navaho");
        iso639.put("nbl", "Ndebele, South; South Ndebele");
        iso639.put("nde", "Ndebele, North; North Ndebele");
        iso639.put("ndo", "Ndonga");
        iso639.put("nds", "Low German; Low Saxon; German, Low; Saxon, Low");
        iso639.put("nep", "Nepali");
        iso639.put("new", "Nepal Bhasa; Newari");
        iso639.put("nia", "Nias");
        iso639.put("nic", "Niger-Kordofanian languages");
        iso639.put("niu", "Niuean");
        iso639.put("dut", "(B)	Dutch; Flemish");
        iso639.put("nld", "(T)");
        iso639.put("nno", "Norwegian Nynorsk; Nynorsk, Norwegian");
        iso639.put("nob", "Bokmål, Norwegian; Norwegian Bokmål");
        iso639.put("nog", "Nogai");
        iso639.put("non", "Norse, Old");
        iso639.put("nor", "Norwegian");
        iso639.put("nqo", "N'Ko");
        iso639.put("nso", "Pedi; Sepedi; Northern Sotho");
        iso639.put("nub", "Nubian languages");
        iso639.put("nwc", "Classical Newari; Old Newari; Classical Nepal Bhasa");
        iso639.put("nya", "Chichewa; Chewa; Nyanja");
        iso639.put("nym", "Nyamwezi");
        iso639.put("nyn", "Nyankole");
        iso639.put("nyo", "Nyoro");
        iso639.put("nzi", "Nzima");
        iso639.put("oci", "Occitan (post 1500)");
        iso639.put("oji", "Ojibwa");
        iso639.put("ori", "Oriya");
        iso639.put("orm", "Oromo");
        iso639.put("osa", "Osage");
        iso639.put("oss", "Ossetian; Ossetic");
        iso639.put("ota", "Turkish, Ottoman (1500-1928)");
        iso639.put("oto", "Otomian languages");
        iso639.put("paa", "Papuan languages");
        iso639.put("pag", "Pangasinan");
        iso639.put("pal", "Pahlavi");
        iso639.put("pam", "Pampanga; Kapampangan");
        iso639.put("pan", "Panjabi; Punjabi");
        iso639.put("pap", "Papiamento");
        iso639.put("pau", "Palauan");
        iso639.put("peo", "Persian, Old (ca.600-400 B.C.)");
        iso639.put("per", "(B)	Persian");
        iso639.put("fas", "(T)");
        iso639.put("phi", "Philippine languages");
        iso639.put("phn", "Phoenician");
        iso639.put("pli", "Pali");
        iso639.put("pol", "Polish");
        iso639.put("pon", "Pohnpeian");
        iso639.put("por", "Portuguese");
        iso639.put("pra", "Prakrit languages");
        iso639.put("pro", "Provençal, Old (to 1500);Occitan, Old (to 1500)");
        iso639.put("pus", "Pushto; Pashto");
        iso639.put("qaa", "qtz	Reserved for local use");
        iso639.put("que", "Quechua");
        iso639.put("raj", "Rajasthani");
        iso639.put("rap", "Rapanui");
        iso639.put("rar", "Rarotongan; Cook Islands Maori");
        iso639.put("roa", "Romance languages");
        iso639.put("roh", "Romansh");
        iso639.put("rom", "Romany");
        iso639.put("rum", "(B)	Romanian; Moldavian; Moldovan");
        iso639.put("ron", "(T)");
        iso639.put("rum", "(B)	Romanian; Moldavian; Moldovan");
        iso639.put("ron", "(T)");
        iso639.put("run", "Rundi");
        iso639.put("rup", "Aromanian; Arumanian; Macedo-Romanian");
        iso639.put("rus", "Russian");
        iso639.put("sad", "Sandawe");
        iso639.put("sag", "Sango");
        iso639.put("sah", "Yakut");
        iso639.put("sai", "South American Indian languages");
        iso639.put("sal", "Salishan languages");
        iso639.put("sam", "Samaritan Aramaic");
        iso639.put("san", "Sanskrit");
        iso639.put("sas", "Sasak");
        iso639.put("sat", "Santali");
        iso639.put("scn", "Sicilian");
        iso639.put("sco", "Scots");
        iso639.put("sel", "Selkup");
        iso639.put("sem", "Semitic languages");
        iso639.put("sga", "Irish, Old (to 900)");
        iso639.put("sgn", "Sign Languages");
        iso639.put("shn", "Shan");
        iso639.put("sid", "Sidamo");
        iso639.put("sin", "Sinhala; Sinhalese");
        iso639.put("sio", "Siouan languages");
        iso639.put("sit", "Sino-Tibetan languages");
        iso639.put("sla", "Slavic languages");
        iso639.put("slo", "(B)	Slovak");
        iso639.put("slk", "(T)");
        iso639.put("slo", "(B)	Slovak");
        iso639.put("slk", "(T)");
        iso639.put("slv", "Slovenian");
        iso639.put("sma", "Southern Sami");
        iso639.put("sme", "Northern Sami");
        iso639.put("smi", "Sami languages");
        iso639.put("smj", "Lule Sami");
        iso639.put("smn", "Inari Sami");
        iso639.put("smo", "Samoan");
        iso639.put("sms", "Skolt Sami");
        iso639.put("sna", "Shona");
        iso639.put("snd", "Sindhi");
        iso639.put("snk", "Soninke");
        iso639.put("sog", "Sogdian");
        iso639.put("som", "Somali");
        iso639.put("son", "Songhai languages");
        iso639.put("sot", "Sotho, Southern");
        iso639.put("spa", "Spanish; Castilian");
        iso639.put("alb", "(B)	Albanian");
        iso639.put("sqi", "(T)");
        iso639.put("srd", "Sardinian");
        iso639.put("srn", "Sranan Tongo");
        iso639.put("srp", "Serbian");
        iso639.put("srr", "Serer");
        iso639.put("ssa", "Nilo-Saharan languages");
        iso639.put("ssw", "Swati");
        iso639.put("suk", "Sukuma");
        iso639.put("sun", "Sundanese");
        iso639.put("sus", "Susu");
        iso639.put("sux", "Sumerian");
        iso639.put("swa", "Swahili");
        iso639.put("swe", "Swedish");
        iso639.put("syc", "Classical Syriac");
        iso639.put("syr", "Syriac");
        iso639.put("tah", "Tahitian");
        iso639.put("tai", "Tai languages");
        iso639.put("tam", "Tamil");
        iso639.put("tat", "Tatar");
        iso639.put("tel", "Telugu");
        iso639.put("tem", "Timne");
        iso639.put("ter", "Tereno");
        iso639.put("tet", "Tetum");
        iso639.put("tgk", "Tajik");
        iso639.put("tgl", "Tagalog");
        iso639.put("tha", "Thai");
        iso639.put("tib", "(B)	Tibetan");
        iso639.put("bod", "(T)");
        iso639.put("tig", "Tigre");
        iso639.put("tir", "Tigrinya");
        iso639.put("tiv", "Tiv");
        iso639.put("tkl", "Tokelau");
        iso639.put("tlh", "Klingon; tlhIngan-Hol");
        iso639.put("tli", "Tlingit");
        iso639.put("tmh", "Tamashek");
        iso639.put("tog", "Tonga (Nyasa)");
        iso639.put("ton", "Tonga (Tonga Islands)");
        iso639.put("tpi", "Tok Pisin");
        iso639.put("tsi", "Tsimshian");
        iso639.put("tsn", "Tswana");
        iso639.put("tso", "Tsonga");
        iso639.put("tuk", "Turkmen");
        iso639.put("tum", "Tumbuka");
        iso639.put("tup", "Tupi languages");
        iso639.put("tur", "Turkish");
        iso639.put("tut", "Altaic languages");
        iso639.put("tvl", "Tuvalu");
        iso639.put("twi", "Twi");
        iso639.put("tyv", "Tuvinian");
        iso639.put("udm", "Udmurt");
        iso639.put("uga", "Ugaritic");
        iso639.put("uig", "Uighur; Uyghur");
        iso639.put("ukr", "Ukrainian");
        iso639.put("umb", "Umbundu");
        iso639.put("und", "Undetermined");
        iso639.put("urd", "Urdu");
        iso639.put("uzb", "Uzbek");
        iso639.put("vai", "Vai");
        iso639.put("ven", "Venda");
        iso639.put("vie", "Vietnamese");
        iso639.put("vol", "Volapük");
        iso639.put("vot", "Votic");
        iso639.put("wak", "Wakashan languages");
        iso639.put("wal", "Wolaitta; Wolaytta");
        iso639.put("war", "Waray");
        iso639.put("was", "Washo");
        iso639.put("wel", "(B)	Welsh");
        iso639.put("cym", "(T)");
        iso639.put("wen", "Sorbian languages");
        iso639.put("wln", "Walloon");
        iso639.put("wol", "Wolof");
        iso639.put("xal", "Kalmyk; Oirat");
        iso639.put("xho", "Xhosa");
        iso639.put("yao", "Yao");
        iso639.put("yap", "Yapese");
        iso639.put("yid", "Yiddish");
        iso639.put("yor", "Yoruba");
        iso639.put("ypk", "Yupik languages");
        iso639.put("zap", "Zapotec");
        iso639.put("zbl", "Blissymbols; Blissymbolics; Bliss");
        iso639.put("zen", "Zenaga");
        iso639.put("zgh", "Standard Moroccan Tamazight");
        iso639.put("zha", "Zhuang; Chuang");
        iso639.put("chi", "Chinese");
        iso639.put("zho", "(T)");
        iso639.put("znd", "Zande languages");
        iso639.put("zul", "Zulu");
        iso639.put("zun", "Zuni");
        iso639.put("zxx", "No linguistic content; Not applicable");
        iso639.put("zza", "Zaza; Dimili; Dimli; Kirdki; Kirmanjki; Zazaki");
    }
}