//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.08.13 at 05:01:13 PM EDT 
//


package com.pqi.responsecompare.edi.mp;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for edi.mp.cssType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="edi.mp.cssType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ISA" type="{}ISAType"/&gt;
 *         &lt;element name="GS" type="{}GSType"/&gt;
 *         &lt;element name="ST" type="{}STType"/&gt;
 *         &lt;element name="BGN" type="{}BGNType"/&gt;
 *         &lt;element name="DTP" type="{}DTPType"/&gt;
 *         &lt;element name="N1" type="{}N1Type" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="INS-ITEMS" type="{}INS-ITEMSType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="SE" type="{}SEType"/&gt;
 *         &lt;element name="GE" type="{}GEType"/&gt;
 *         &lt;element name="IEA" type="{}IEAType"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "edi.mp.cssType", propOrder = {
    "isa",
    "gs",
    "st",
    "bgn",
    "dtp",
    "n1",
    "insitems",
    "se",
    "ge",
    "iea"
})
public class EdiMpCssType {

    @XmlElement(name = "ISA", required = true)
    protected ISAType isa;
    @XmlElement(name = "GS", required = true)
    protected GSType gs;
    @XmlElement(name = "ST", required = true)
    protected STType st;
    @XmlElement(name = "BGN", required = true)
    protected BGNType bgn;
    @XmlElement(name = "DTP", required = true)
    protected DTPType dtp;
    @XmlElement(name = "N1")
    protected List<N1Type> n1;
    @XmlElement(name = "INS-ITEMS")
    protected List<INSITEMSType> insitems;
    @XmlElement(name = "SE", required = true)
    protected SEType se;
    @XmlElement(name = "GE", required = true)
    protected GEType ge;
    @XmlElement(name = "IEA", required = true)
    protected IEAType iea;

    /**
     * Gets the value of the isa property.
     * 
     * @return
     *     possible object is
     *     {@link ISAType }
     *     
     */
    public ISAType getISA() {
        return isa;
    }

    /**
     * Sets the value of the isa property.
     * 
     * @param value
     *     allowed object is
     *     {@link ISAType }
     *     
     */
    public void setISA(ISAType value) {
        this.isa = value;
    }

    /**
     * Gets the value of the gs property.
     * 
     * @return
     *     possible object is
     *     {@link GSType }
     *     
     */
    public GSType getGS() {
        return gs;
    }

    /**
     * Sets the value of the gs property.
     * 
     * @param value
     *     allowed object is
     *     {@link GSType }
     *     
     */
    public void setGS(GSType value) {
        this.gs = value;
    }

    /**
     * Gets the value of the st property.
     * 
     * @return
     *     possible object is
     *     {@link STType }
     *     
     */
    public STType getST() {
        return st;
    }

    /**
     * Sets the value of the st property.
     * 
     * @param value
     *     allowed object is
     *     {@link STType }
     *     
     */
    public void setST(STType value) {
        this.st = value;
    }

    /**
     * Gets the value of the bgn property.
     * 
     * @return
     *     possible object is
     *     {@link BGNType }
     *     
     */
    public BGNType getBGN() {
        return bgn;
    }

    /**
     * Sets the value of the bgn property.
     * 
     * @param value
     *     allowed object is
     *     {@link BGNType }
     *     
     */
    public void setBGN(BGNType value) {
        this.bgn = value;
    }

    /**
     * Gets the value of the dtp property.
     * 
     * @return
     *     possible object is
     *     {@link DTPType }
     *     
     */
    public DTPType getDTP() {
        return dtp;
    }

    /**
     * Sets the value of the dtp property.
     * 
     * @param value
     *     allowed object is
     *     {@link DTPType }
     *     
     */
    public void setDTP(DTPType value) {
        this.dtp = value;
    }

    /**
     * Gets the value of the n1 property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the n1 property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getN1().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link N1Type }
     * 
     * 
     */
    public List<N1Type> getN1() {
        if (n1 == null) {
            n1 = new ArrayList<N1Type>();
        }
        return this.n1;
    }

    /**
     * Gets the value of the insitems property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the insitems property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getINSITEMS().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link INSITEMSType }
     * 
     * 
     */
    public List<INSITEMSType> getINSITEMS() {
        if (insitems == null) {
            insitems = new ArrayList<INSITEMSType>();
        }
        return this.insitems;
    }

    /**
     * Gets the value of the se property.
     * 
     * @return
     *     possible object is
     *     {@link SEType }
     *     
     */
    public SEType getSE() {
        return se;
    }

    /**
     * Sets the value of the se property.
     * 
     * @param value
     *     allowed object is
     *     {@link SEType }
     *     
     */
    public void setSE(SEType value) {
        this.se = value;
    }

    /**
     * Gets the value of the ge property.
     * 
     * @return
     *     possible object is
     *     {@link GEType }
     *     
     */
    public GEType getGE() {
        return ge;
    }

    /**
     * Sets the value of the ge property.
     * 
     * @param value
     *     allowed object is
     *     {@link GEType }
     *     
     */
    public void setGE(GEType value) {
        this.ge = value;
    }

    /**
     * Gets the value of the iea property.
     * 
     * @return
     *     possible object is
     *     {@link IEAType }
     *     
     */
    public IEAType getIEA() {
        return iea;
    }

    /**
     * Sets the value of the iea property.
     * 
     * @param value
     *     allowed object is
     *     {@link IEAType }
     *     
     */
    public void setIEA(IEAType value) {
        this.iea = value;
    }

}
