//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.08.13 at 05:01:13 PM EDT 
//


package com.pqi.responsecompare.edi.mp;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GEType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GEType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Number-of-Transaction-Sets-Included" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Group-Control-Number" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GEType", propOrder = {
    "numberOfTransactionSetsIncluded",
    "groupControlNumber"
})
public class GEType {

    @XmlElement(name = "Number-of-Transaction-Sets-Included", required = true)
    protected String numberOfTransactionSetsIncluded;
    @XmlElement(name = "Group-Control-Number", required = true)
    protected String groupControlNumber;

    /**
     * Gets the value of the numberOfTransactionSetsIncluded property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumberOfTransactionSetsIncluded() {
        return numberOfTransactionSetsIncluded;
    }

    /**
     * Sets the value of the numberOfTransactionSetsIncluded property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumberOfTransactionSetsIncluded(String value) {
        this.numberOfTransactionSetsIncluded = value;
    }

    /**
     * Gets the value of the groupControlNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGroupControlNumber() {
        return groupControlNumber;
    }

    /**
     * Sets the value of the groupControlNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGroupControlNumber(String value) {
        this.groupControlNumber = value;
    }

}
