//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.08.13 at 05:01:13 PM EDT 
//


package com.pqi.responsecompare.edi.mp;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for INS-ITEMSType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="INS-ITEMSType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice maxOccurs="unbounded" minOccurs="0"&gt;
 *         &lt;element name="INS" type="{}INSType"/&gt;
 *         &lt;element name="REF" type="{}REFType"/&gt;
 *         &lt;element name="DTP" type="{}DTPType"/&gt;
 *         &lt;element name="NM1" type="{}NM1Type"/&gt;
 *         &lt;element name="DMG" type="{}DMGType"/&gt;
 *         &lt;element name="AMT" type="{}AMTType"/&gt;
 *         &lt;element name="LUI" type="{}LUIType"/&gt;
 *         &lt;element name="HD" type="{}HDType"/&gt;
 *         &lt;element name="LS" type="{}LSType"/&gt;
 *         &lt;element name="lx-tag" type="{}lx-tagType"/&gt;
 *         &lt;element name="LE" type="{}LEType"/&gt;
 *         &lt;element name="N3" type="{}N3Type"/&gt;
 *         &lt;element name="N4" type="{}N4Type"/&gt;
 *         &lt;element name="PER" type="{}PERType"/&gt;
 *       &lt;/choice&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "INS-ITEMSType", propOrder = {
    "insOrREFOrDTP"
})
public class INSITEMSType {

    @XmlElements({
        @XmlElement(name = "INS", type = INSType.class),
        @XmlElement(name = "REF", type = REFType.class),
        @XmlElement(name = "DTP", type = DTPType.class),
        @XmlElement(name = "NM1", type = NM1Type.class),
        @XmlElement(name = "DMG", type = DMGType.class),
        @XmlElement(name = "AMT", type = AMTType.class),
        @XmlElement(name = "LUI", type = LUIType.class),
        @XmlElement(name = "HD", type = HDType.class),
        @XmlElement(name = "LS", type = LSType.class),
        @XmlElement(name = "lx-tag", type = LxTagType.class),
        @XmlElement(name = "LE", type = LEType.class),
        @XmlElement(name = "N3", type = N3Type.class),
        @XmlElement(name = "N4", type = N4Type.class),
        @XmlElement(name = "PER", type = PERType.class)
    })
    protected List<Object> insOrREFOrDTP;

    /**
     * Gets the value of the insOrREFOrDTP property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the insOrREFOrDTP property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getINSOrREFOrDTP().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link INSType }
     * {@link REFType }
     * {@link DTPType }
     * {@link NM1Type }
     * {@link DMGType }
     * {@link AMTType }
     * {@link LUIType }
     * {@link HDType }
     * {@link LSType }
     * {@link LxTagType }
     * {@link LEType }
     * {@link N3Type }
     * {@link N4Type }
     * {@link PERType }
     * 
     * 
     */
    public List<Object> getINSOrREFOrDTP() {
        if (insOrREFOrDTP == null) {
            insOrREFOrDTP = new ArrayList<Object>();
        }
        return this.insOrREFOrDTP;
    }

}
