//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.08.13 at 05:01:13 PM EDT 
//


package com.pqi.responsecompare.edi.mp;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for INSType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="INSType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Member-Indicator" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Individual-Relationship-Code" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Maintenance-Type-Code"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;enumeration value="001"/&gt;
 *               &lt;enumeration value="024"/&gt;
 *               &lt;enumeration value="021"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="Maintenance-Reason-Code" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Benefit-Status-Code" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Employment-Status-Code"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;enumeration value="AC"/&gt;
 *               &lt;enumeration value="TE"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="Yes-no-Condition-or-Response-Code"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;enumeration value="N"/&gt;
 *               &lt;enumeration value="Y"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="Confidentiality-Code" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "INSType", propOrder = {
    "memberIndicator",
    "individualRelationshipCode",
    "maintenanceTypeCode",
    "maintenanceReasonCode",
    "benefitStatusCode",
    "employmentStatusCode",
    "yesNoConditionOrResponseCode",
    "confidentialityCode"
})
public class INSType {

    @XmlElement(name = "Member-Indicator", required = true)
    protected String memberIndicator;
    @XmlElement(name = "Individual-Relationship-Code", required = true)
    protected String individualRelationshipCode;
    @XmlElement(name = "Maintenance-Type-Code", required = true)
    protected String maintenanceTypeCode;
    @XmlElement(name = "Maintenance-Reason-Code", required = true)
    protected String maintenanceReasonCode;
    @XmlElement(name = "Benefit-Status-Code", required = true)
    protected String benefitStatusCode;
    @XmlElement(name = "Employment-Status-Code", required = true)
    protected String employmentStatusCode;
    @XmlElement(name = "Yes-no-Condition-or-Response-Code", required = true)
    protected String yesNoConditionOrResponseCode;
    @XmlElement(name = "Confidentiality-Code")
    protected String confidentialityCode;

    /**
     * Gets the value of the memberIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMemberIndicator() {
        return memberIndicator;
    }

    /**
     * Sets the value of the memberIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMemberIndicator(String value) {
        this.memberIndicator = value;
    }

    /**
     * Gets the value of the individualRelationshipCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIndividualRelationshipCode() {
        return individualRelationshipCode;
    }

    /**
     * Sets the value of the individualRelationshipCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIndividualRelationshipCode(String value) {
        this.individualRelationshipCode = value;
    }

    /**
     * Gets the value of the maintenanceTypeCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaintenanceTypeCode() {
        return maintenanceTypeCode;
    }

    /**
     * Sets the value of the maintenanceTypeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaintenanceTypeCode(String value) {
        this.maintenanceTypeCode = value;
    }

    /**
     * Gets the value of the maintenanceReasonCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaintenanceReasonCode() {
        return maintenanceReasonCode;
    }

    /**
     * Sets the value of the maintenanceReasonCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaintenanceReasonCode(String value) {
        this.maintenanceReasonCode = value;
    }

    /**
     * Gets the value of the benefitStatusCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBenefitStatusCode() {
        return benefitStatusCode;
    }

    /**
     * Sets the value of the benefitStatusCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBenefitStatusCode(String value) {
        this.benefitStatusCode = value;
    }

    /**
     * Gets the value of the employmentStatusCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmploymentStatusCode() {
        return employmentStatusCode;
    }

    /**
     * Sets the value of the employmentStatusCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmploymentStatusCode(String value) {
        this.employmentStatusCode = value;
    }

    /**
     * Gets the value of the yesNoConditionOrResponseCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getYesNoConditionOrResponseCode() {
        return yesNoConditionOrResponseCode;
    }

    /**
     * Sets the value of the yesNoConditionOrResponseCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setYesNoConditionOrResponseCode(String value) {
        this.yesNoConditionOrResponseCode = value;
    }

    /**
     * Gets the value of the confidentialityCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConfidentialityCode() {
        return confidentialityCode;
    }

    /**
     * Sets the value of the confidentialityCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConfidentialityCode(String value) {
        this.confidentialityCode = value;
    }

}
