//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.08.13 at 05:01:13 PM EDT 
//


package com.pqi.responsecompare.edi.mp;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ISAType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ISAType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Authorization-Information-Qualifier" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Author-Information" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Security-Info-Qual" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Security-Information" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Interchange-ID-Qual1" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Interchange-Sender-ID" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Interchange-ID-Qual2" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Interchange-ReceiverID" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Interchange-Date" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Interchange-Time" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Interchange-Ctrl-Stand-Ident" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Inter-Ctrl-Version-Number" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Inter-Ctrl-Number" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Ack-Requested" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Usage-Indicator" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Component-Elem-Sepera" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ISAType", propOrder = {
    "authorizationInformationQualifier",
    "authorInformation",
    "securityInfoQual",
    "securityInformation",
    "interchangeIDQual1",
    "interchangeSenderID",
    "interchangeIDQual2",
    "interchangeReceiverID",
    "interchangeDate",
    "interchangeTime",
    "interchangeCtrlStandIdent",
    "interCtrlVersionNumber",
    "interCtrlNumber",
    "ackRequested",
    "usageIndicator",
    "componentElemSepera"
})
public class ISAType {

    @XmlElement(name = "Authorization-Information-Qualifier", required = true)
    protected String authorizationInformationQualifier;
    @XmlElement(name = "Author-Information", required = true)
    protected String authorInformation;
    @XmlElement(name = "Security-Info-Qual", required = true)
    protected String securityInfoQual;
    @XmlElement(name = "Security-Information", required = true)
    protected String securityInformation;
    @XmlElement(name = "Interchange-ID-Qual1", required = true)
    protected String interchangeIDQual1;
    @XmlElement(name = "Interchange-Sender-ID", required = true)
    protected String interchangeSenderID;
    @XmlElement(name = "Interchange-ID-Qual2", required = true)
    protected String interchangeIDQual2;
    @XmlElement(name = "Interchange-ReceiverID", required = true)
    protected String interchangeReceiverID;
    @XmlElement(name = "Interchange-Date", required = true)
    protected String interchangeDate;
    @XmlElement(name = "Interchange-Time", required = true)
    protected String interchangeTime;
    @XmlElement(name = "Interchange-Ctrl-Stand-Ident", required = true)
    protected String interchangeCtrlStandIdent;
    @XmlElement(name = "Inter-Ctrl-Version-Number", required = true)
    protected String interCtrlVersionNumber;
    @XmlElement(name = "Inter-Ctrl-Number", required = true)
    protected String interCtrlNumber;
    @XmlElement(name = "Ack-Requested", required = true)
    protected String ackRequested;
    @XmlElement(name = "Usage-Indicator", required = true)
    protected String usageIndicator;
    @XmlElement(name = "Component-Elem-Sepera", required = true)
    protected String componentElemSepera;

    /**
     * Gets the value of the authorizationInformationQualifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuthorizationInformationQualifier() {
        return authorizationInformationQualifier;
    }

    /**
     * Sets the value of the authorizationInformationQualifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuthorizationInformationQualifier(String value) {
        this.authorizationInformationQualifier = value;
    }

    /**
     * Gets the value of the authorInformation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuthorInformation() {
        return authorInformation;
    }

    /**
     * Sets the value of the authorInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuthorInformation(String value) {
        this.authorInformation = value;
    }

    /**
     * Gets the value of the securityInfoQual property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSecurityInfoQual() {
        return securityInfoQual;
    }

    /**
     * Sets the value of the securityInfoQual property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSecurityInfoQual(String value) {
        this.securityInfoQual = value;
    }

    /**
     * Gets the value of the securityInformation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSecurityInformation() {
        return securityInformation;
    }

    /**
     * Sets the value of the securityInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSecurityInformation(String value) {
        this.securityInformation = value;
    }

    /**
     * Gets the value of the interchangeIDQual1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInterchangeIDQual1() {
        return interchangeIDQual1;
    }

    /**
     * Sets the value of the interchangeIDQual1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInterchangeIDQual1(String value) {
        this.interchangeIDQual1 = value;
    }

    /**
     * Gets the value of the interchangeSenderID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInterchangeSenderID() {
        return interchangeSenderID;
    }

    /**
     * Sets the value of the interchangeSenderID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInterchangeSenderID(String value) {
        this.interchangeSenderID = value;
    }

    /**
     * Gets the value of the interchangeIDQual2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInterchangeIDQual2() {
        return interchangeIDQual2;
    }

    /**
     * Sets the value of the interchangeIDQual2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInterchangeIDQual2(String value) {
        this.interchangeIDQual2 = value;
    }

    /**
     * Gets the value of the interchangeReceiverID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInterchangeReceiverID() {
        return interchangeReceiverID;
    }

    /**
     * Sets the value of the interchangeReceiverID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInterchangeReceiverID(String value) {
        this.interchangeReceiverID = value;
    }

    /**
     * Gets the value of the interchangeDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInterchangeDate() {
        return interchangeDate;
    }

    /**
     * Sets the value of the interchangeDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInterchangeDate(String value) {
        this.interchangeDate = value;
    }

    /**
     * Gets the value of the interchangeTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInterchangeTime() {
        return interchangeTime;
    }

    /**
     * Sets the value of the interchangeTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInterchangeTime(String value) {
        this.interchangeTime = value;
    }

    /**
     * Gets the value of the interchangeCtrlStandIdent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInterchangeCtrlStandIdent() {
        return interchangeCtrlStandIdent;
    }

    /**
     * Sets the value of the interchangeCtrlStandIdent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInterchangeCtrlStandIdent(String value) {
        this.interchangeCtrlStandIdent = value;
    }

    /**
     * Gets the value of the interCtrlVersionNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInterCtrlVersionNumber() {
        return interCtrlVersionNumber;
    }

    /**
     * Sets the value of the interCtrlVersionNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInterCtrlVersionNumber(String value) {
        this.interCtrlVersionNumber = value;
    }

    /**
     * Gets the value of the interCtrlNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInterCtrlNumber() {
        return interCtrlNumber;
    }

    /**
     * Sets the value of the interCtrlNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInterCtrlNumber(String value) {
        this.interCtrlNumber = value;
    }

    /**
     * Gets the value of the ackRequested property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAckRequested() {
        return ackRequested;
    }

    /**
     * Sets the value of the ackRequested property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAckRequested(String value) {
        this.ackRequested = value;
    }

    /**
     * Gets the value of the usageIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUsageIndicator() {
        return usageIndicator;
    }

    /**
     * Sets the value of the usageIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUsageIndicator(String value) {
        this.usageIndicator = value;
    }

    /**
     * Gets the value of the componentElemSepera property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComponentElemSepera() {
        return componentElemSepera;
    }

    /**
     * Sets the value of the componentElemSepera property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComponentElemSepera(String value) {
        this.componentElemSepera = value;
    }

}
