//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.08.13 at 05:01:13 PM EDT 
//


package com.pqi.responsecompare.edi.mp;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.pqi.responsecompare.edi.mp package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _EdiMpCss_QNAME = new QName("", "edi.mp.css");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.pqi.responsecompare.edi.mp
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link EdiMpCssType }
     * 
     */
    public EdiMpCssType createEdiMpCssType() {
        return new EdiMpCssType();
    }

    /**
     * Create an instance of {@link LSType }
     * 
     */
    public LSType createLSType() {
        return new LSType();
    }

    /**
     * Create an instance of {@link N1Type }
     * 
     */
    public N1Type createN1Type() {
        return new N1Type();
    }

    /**
     * Create an instance of {@link NM1Type }
     * 
     */
    public NM1Type createNM1Type() {
        return new NM1Type();
    }

    /**
     * Create an instance of {@link PERType }
     * 
     */
    public PERType createPERType() {
        return new PERType();
    }

    /**
     * Create an instance of {@link STType }
     * 
     */
    public STType createSTType() {
        return new STType();
    }

    /**
     * Create an instance of {@link INSType }
     * 
     */
    public INSType createINSType() {
        return new INSType();
    }

    /**
     * Create an instance of {@link DTPType }
     * 
     */
    public DTPType createDTPType() {
        return new DTPType();
    }

    /**
     * Create an instance of {@link HDType }
     * 
     */
    public HDType createHDType() {
        return new HDType();
    }

    /**
     * Create an instance of {@link LXType }
     * 
     */
    public LXType createLXType() {
        return new LXType();
    }

    /**
     * Create an instance of {@link N4Type }
     * 
     */
    public N4Type createN4Type() {
        return new N4Type();
    }

    /**
     * Create an instance of {@link IEAType }
     * 
     */
    public IEAType createIEAType() {
        return new IEAType();
    }

    /**
     * Create an instance of {@link LxTagType }
     * 
     */
    public LxTagType createLxTagType() {
        return new LxTagType();
    }

    /**
     * Create an instance of {@link AMTType }
     * 
     */
    public AMTType createAMTType() {
        return new AMTType();
    }

    /**
     * Create an instance of {@link INSITEMSType }
     * 
     */
    public INSITEMSType createINSITEMSType() {
        return new INSITEMSType();
    }

    /**
     * Create an instance of {@link GEType }
     * 
     */
    public GEType createGEType() {
        return new GEType();
    }

    /**
     * Create an instance of {@link DMGType }
     * 
     */
    public DMGType createDMGType() {
        return new DMGType();
    }

    /**
     * Create an instance of {@link GSType }
     * 
     */
    public GSType createGSType() {
        return new GSType();
    }

    /**
     * Create an instance of {@link LUIType }
     * 
     */
    public LUIType createLUIType() {
        return new LUIType();
    }

    /**
     * Create an instance of {@link N3Type }
     * 
     */
    public N3Type createN3Type() {
        return new N3Type();
    }

    /**
     * Create an instance of {@link REFType }
     * 
     */
    public REFType createREFType() {
        return new REFType();
    }

    /**
     * Create an instance of {@link ISAType }
     * 
     */
    public ISAType createISAType() {
        return new ISAType();
    }

    /**
     * Create an instance of {@link BGNType }
     * 
     */
    public BGNType createBGNType() {
        return new BGNType();
    }

    /**
     * Create an instance of {@link LEType }
     * 
     */
    public LEType createLEType() {
        return new LEType();
    }

    /**
     * Create an instance of {@link SEType }
     * 
     */
    public SEType createSEType() {
        return new SEType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EdiMpCssType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "edi.mp.css")
    public JAXBElement<EdiMpCssType> createEdiMpCss(EdiMpCssType value) {
        return new JAXBElement<EdiMpCssType>(_EdiMpCss_QNAME, EdiMpCssType.class, null, value);
    }

}
