//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.08.13 at 05:01:13 PM EDT 
//


package com.pqi.responsecompare.edi.mp;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for REFType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="REFType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Reference-Identification-Qualifier"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;enumeration value="0F"/&gt;
 *               &lt;enumeration value="1L"/&gt;
 *               &lt;enumeration value="3H"/&gt;
 *               &lt;enumeration value="DX"/&gt;
 *               &lt;enumeration value="ZZ"/&gt;
 *               &lt;enumeration value="F6"/&gt;
 *               &lt;enumeration value="XX1"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="Reference-Identification" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "REFType", propOrder = {
    "referenceIdentificationQualifier",
    "referenceIdentification"
})
public class REFType {

    @XmlElement(name = "Reference-Identification-Qualifier", required = true)
    protected String referenceIdentificationQualifier;
    @XmlElement(name = "Reference-Identification", required = true)
    protected String referenceIdentification;

    /**
     * Gets the value of the referenceIdentificationQualifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReferenceIdentificationQualifier() {
        return referenceIdentificationQualifier;
    }

    /**
     * Sets the value of the referenceIdentificationQualifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReferenceIdentificationQualifier(String value) {
        this.referenceIdentificationQualifier = value;
    }

    /**
     * Gets the value of the referenceIdentification property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReferenceIdentification() {
        return referenceIdentification;
    }

    /**
     * Sets the value of the referenceIdentification property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReferenceIdentification(String value) {
        this.referenceIdentification = value;
    }

}
