//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.08.13 at 05:01:13 PM EDT 
//


package com.pqi.responsecompare.edi.mp;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SEType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SEType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Number-of-Included-Segments" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Transaction-Set-Control-Number" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SEType", propOrder = {
    "numberOfIncludedSegments",
    "transactionSetControlNumber"
})
public class SEType {

    @XmlElement(name = "Number-of-Included-Segments", required = true)
    protected String numberOfIncludedSegments;
    @XmlElement(name = "Transaction-Set-Control-Number", required = true)
    protected String transactionSetControlNumber;

    /**
     * Gets the value of the numberOfIncludedSegments property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumberOfIncludedSegments() {
        return numberOfIncludedSegments;
    }

    /**
     * Sets the value of the numberOfIncludedSegments property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumberOfIncludedSegments(String value) {
        this.numberOfIncludedSegments = value;
    }

    /**
     * Gets the value of the transactionSetControlNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransactionSetControlNumber() {
        return transactionSetControlNumber;
    }

    /**
     * Sets the value of the transactionSetControlNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransactionSetControlNumber(String value) {
        this.transactionSetControlNumber = value;
    }

}
