//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.08.13 at 05:01:13 PM EDT 
//


package com.pqi.responsecompare.edi.mp;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for STType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="STType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Transaction-Set-Identifier-Code" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Transaction-Set-Control-Number" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Implementation-Convention-Reference" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "STType", propOrder = {
    "transactionSetIdentifierCode",
    "transactionSetControlNumber",
    "implementationConventionReference"
})
public class STType {

    @XmlElement(name = "Transaction-Set-Identifier-Code", required = true)
    protected String transactionSetIdentifierCode;
    @XmlElement(name = "Transaction-Set-Control-Number", required = true)
    protected String transactionSetControlNumber;
    @XmlElement(name = "Implementation-Convention-Reference", required = true)
    protected String implementationConventionReference;

    /**
     * Gets the value of the transactionSetIdentifierCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransactionSetIdentifierCode() {
        return transactionSetIdentifierCode;
    }

    /**
     * Sets the value of the transactionSetIdentifierCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransactionSetIdentifierCode(String value) {
        this.transactionSetIdentifierCode = value;
    }

    /**
     * Gets the value of the transactionSetControlNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransactionSetControlNumber() {
        return transactionSetControlNumber;
    }

    /**
     * Sets the value of the transactionSetControlNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransactionSetControlNumber(String value) {
        this.transactionSetControlNumber = value;
    }

    /**
     * Gets the value of the implementationConventionReference property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImplementationConventionReference() {
        return implementationConventionReference;
    }

    /**
     * Sets the value of the implementationConventionReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImplementationConventionReference(String value) {
        this.implementationConventionReference = value;
    }

}
